package ee.hitsa.ois.enums;

public enum HigherProtocolAssessment {
    KORGHINDAMINE_0,
    KORGHINDAMINE_1,
    KORGHINDAMINE_2,
    KORGHINDAMINE_3,
    KORGHINDAMINE_4,
    KORGHINDAMINE_5,
    KORGHINDAMINE_A,
    KORGHINDAMINE_M,
    KORGHINDAMINE_MI
}
